version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3

    # Limit to the `main` branch
    target-branch: "main"
    commit-message:
      prefix: "ci"
      include: "scope"
